image: docker:latest

services:
  - name: docker:dind
    command: ["--tls=false"]

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

test:
  script:
    - docker info
    - docker compose build
    - echo "build complete"
  tags:
    - maven

