stages:
  - test
  - build
  - deploy

test_job:
  stage: test
  tags:
    - maven
  before_script:
    - cd backend
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install -r requirements.txt
    - pip install pytest
  script:
    - echo "Running tests..."
    - pytest

build_job:
  stage: build
  tags:
    - maven
  script:
    - echo "Building the application..."
    - docker compose build

deploy_job:
  stage: deploy
  tags:
    - maven
  script:
    - echo "Deploying to production..."
    - docker compose up -d
  only:
    - main
    - backend
