stages:
  - test
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - df
  - cat /etc/resolv.conf
  - cat /etc/hosts

test:
  tags:
    - hetzner
  stage: test
  image: node:20 # Node.js for the tests
  script:
    # Install dependencies and run tests for both frontend and backend
    - cd frontend && npm install --legacy-peer-deps && npm test
    - apt-get update && apt-get install -y python3 python3-pip
    - pip3 install pytest
    - cd ../backend && pytest tests/
  only:
    - deployment

build:
  tags:
    - hetzner
  image: docker:latest
  stage: build
  before_script:
    - export COMPOSE_BAKE=true
  script:
    - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USER --password-stdin
    - docker compose build
    - docker tag backend:latest ${DOCKER_USER}/backend:latest
    - docker tag ollama:latest ${DOCKER_USER}/ollama:latest
    - docker tag frontend:latest ${DOCKER_USER}/frontend:latest
    - docker push ${DOCKER_USER}/backend:latest
    - docker push ${DOCKER_USER}/ollama:latest
    - docker push ${DOCKER_USER}/frontend:latest
  only:
    - deployment

deploy:
  tags:
    - hetzner
  stage: deploy
  script:
    - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USER --password-stdin
    - docker pull ${DOCKER_USERE}/backend:latest
    - docker pull ${DOCKER_USERE}/ollama:latest
    - docker pull ${DOCKER_USER}/frontend:latest
    - docker compose up
  only:
    - deployment
