image: python:3.11

test:
  script:
    - echo "hello world"
    - python --version
    - wget -qO- https://astral.sh/uv/install.sh | sh
    - source $HOME/.local/bin/env
    - cd backend
    - echo "REACT_APP_API_KEY=test" > .env
    - ls -a
    - pytest
  tags:
    - maven

