stages:
  - build
  - test

build:
  stage: build
  script:
    - apt-get clean
    - docker system prune -a
    - rm -rf /tmp/*
    - docker compose build
  tags:
    - toms-local-runner

test:
  stage: test
  script:
    - docker compose up -d
    - docker exec sweng25_group_23_ibm-backend-1 pytest
    - docker compose down
  tags:
    - toms-local-runner
