image: docker:24.0.7

variables:
  # Disable TLS since we're running locally
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: unix:///var/run/docker.sock
  DOCKER_DRIVER: overlay2

services:
  - name: docker:24.0.7-dind
    command: ["--tls=false"]

before_script:
  - docker info

stages:
  - build
  - test

build:
  stage: build
  script:
    - docker compose build
  tags:
    - toms-local-runner

test:
  stage: test
  script:
    - docker compose up -d
    - docker exec sweng25_group_23_ibm-backend-1 pytest
    - docker compose down
  tags:
    - toms-local-runner
