image: docker:24.0.7

services:
  - docker:24.0.7-dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

stages:
  - install
  - test
  - deploy

# Backend Tests
test-backend:
  stage: test
  image: python:3.9
  before_script:
    - cd backend
    - python -m pip install --upgrade pip  # Ensure latest pip version
    - pip install --no-cache-dir -r requirements.txt  # Install dependencies efficiently
  script:
    - pytest tests/
  artifacts:
    reports:
      junit: backend/reports/test-results.xml

# Frontend Tests
frontend-tests:
  stage: test
  image: node:18
  before_script:
    - cd frontend
    - npm install
  script:
    - npm test
  artifacts:
    reports:
      junit: frontend/test-results.xml
