stages:
  - test
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - df
  - cat /etc/resolv.conf
  - cat /etc/hosts

test:
  tags:
    - hetzner
  stage: test
  image: node:20 # Node.js for the tests
  script:
    # Install dependencies and run tests for both frontend and backend
    - cd frontend && npm install --legacy-peer-deps && npm test
    - apt-get update && apt-get install -y python3 python3-pip
    - pip3 install pytest
    - cd ../backend && pytest tests/
  only:
    - deployment

build:
  tags:
    - hetzner
  image: docker:latest
  stage: build
  before_script:
    - export COMPOSE_BAKE=true
  script:
    - docker compose build
  only:
    - deployment

deploy:
  tags:
    - hetzner
  stage: deploy
  script:
    - echo "Test Deploying app"
    - deployment # or 'deployment' if you're deploying from that branch
  only:
    - deployment
