image: docker:24.0.7

services:
  - docker:24.0.7-dind

before_script:
  - docker info

stages:
  - build
  - test

build:
  stage: build
  script:
    - docker compose build
  tags:
    - toms-local-runner

test:
  stage: test
  script:
    - docker compose up -d
    - docker exec sweng25_group_23_ibm-backend-1 pytest
    - docker compose down
  tags:
    - toms-local-runner
