image: python:3.11

test:
  script:
    - echo "hello world"
    - python --version
    - wget -qO- https://astral.sh/uv/install.sh | sh
    - source $HOME/.local/bin/env
    - cd backend
    - cat pyproject.toml
    - rm -f uv.lock
    - rm -f .venv
    - uv cache clean
    - uv sync --reinstall
    - echo "REACT_APP_API_KEY=test" > .env
    - pytest
  tags:
    - maven

