variables:
  DOCKER_DRIVER: overlay2

before_script:
  - df
  - cat /etc/resolv.conf
  - cat /etc/hosts
  
stages:
  - test
  - build
  

backend-tests:
  image: python:3.11
  stage: test
  script:
    - wget -qO- https://astral.sh/uv/install.sh | sh
    - source $HOME/.local/bin/env
    - echo "REACT_APP_API_KEY=test\nREACT_APP_BACKEND_URL=http://localhost:3000" > .env
    - cd backend
    - uv sync
    - source .venv/bin/activate
    - pytest
  tags:
    - google-5gb

frontend-tests:
  image: node:18
  stage: test
  before_script:
    - cd frontend
    - npm install
  script:
    - npm test
  tags:
    - google-5gb


build:
  image: docker:latest
  stage: build
  before_script:
    - docker version
  script:
    - echo "REACT_APP_API_KEY=test\nREACT_APP_BACKEND_URL=http://localhost:3000" > .env
    - cd backend
    - export COMPOSE_BAKE=true
    - docker compose build
  tags:
    - google-5gb

