variables:
  DOCKER_DRIVER: overlay2

before_script:
  - df
  - cat /etc/resolv.conf
  - cat /etc/hosts

deploiement:
  image: docker:latest
  before_script:
    - docker version
  script:
    - docker info


# image: python:3.11

# services:
#   - docker:dind

# stages:
#   - build

# variables:
#   DOCKER_DRIVER: overlay2

# before_script:
#   - apt-get update && apt-get install -y docker.io

# build-test:
#   stage: build
#   script:
#     - docker info
#   tags:
#     - google-5gb

# image: python:3.11

# stages:
#   - tests
#   - build

# test-job:
#   stage: tests
#   script:
#     - wget -qO- https://astral.sh/uv/install.sh | sh
#     - source $HOME/.local/bin/env
#     - echo "REACT_APP_API_KEY=test\nREACT_APP_BACKEND_URL=http://localhost:3000" > .env
#     - cd backend
#     - uv sync
#     - source .venv/bin/activate
#     - pytest
#   tags:
#     - google-5gb

# build-job:
#   stage: build
#   script:
#     - echo "REACT_APP_API_KEY=test\nREACT_APP_BACKEND_URL=http://localhost:3000" > .env
#     - cd backend
#     - docker info
#     # - docker compose build
#   tags:
#     - google-5gb
