stages:
  - test
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - df
  - cat /etc/resolv.conf
  - cat /etc/hosts

frontend_test:
  tags:
    - hetzner
  stage: test
  image: node:20
  script:
    - cd frontend
    - npm install --legacy-peer-deps
    - npx jest
  only:
    - main

#backend_test:
#  tags:
#    - hetzner
#  stage: test
#  image: python:3.11
#  script:
#    - apt-get update && apt-get install -y python3-venv
#    - cd backend
#    - python3 -m venv .venv
#    - source .venv/bin/activate
#    - pip install -r requirements.txt
#    - pip install pytest
#    - pytest -v --maxfail=1 --disable-warnings
#  only:
#    - main
build:
  tags:
    - hetzner
  image: docker:latest
  stage: build
  before_script:
    - export COMPOSE_BAKE=true
    - cp $ENV_PATH .env
    - cp $ENV_PATH frontend/.env
  script:
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin
    - docker compose build
    - docker tag sweng25_group_23_ibm-backend:latest ${DOCKER_USER}/sweng25_group_23_ibm-backend:latest
    - docker tag sweng25_group_23_ibm-ollama:latest ${DOCKER_USER}/sweng25_group_23_ibm-ollama:latest
    - docker tag sweng25_group_23_ibm-frontend:latest ${DOCKER_USER}/sweng25_group_23_ibm-frontend:latest
    - docker push ${DOCKER_USER}/sweng25_group_23_ibm-backend:latest
    - docker push ${DOCKER_USER}/sweng25_group_23_ibm-ollama:latest
    - docker push ${DOCKER_USER}/sweng25_group_23_ibm-frontend:latest
  only:
    - main

deploy:
  tags:
    - hetzner
  stage: deploy
  before_script:
    - export COMPOSE_BAKE=true
    - cp $ENV_PATH .env
    - cp $ENV_PATH frontend/.env
    - rm -rf backend/chroma
  script:
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin
    - docker pull ${DOCKER_USER}/sweng25_group_23_ibm-backend:latest
    - docker pull ${DOCKER_USER}/sweng25_group_23_ibm-ollama:latest
    - docker pull ${DOCKER_USER}/sweng25_group_23_ibm-frontend:latest
    - docker compose -f docker-compose-deploy.yml up --build -d
  only:
    - main
