services:
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - backend-net
    volumes:
      - ./backend:/backend-code
    depends_on:
      - ollama
    command: gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --timeout 120 --bind 0.0.0.0:8000
    deploy:
      resources:
        limits:
          memory: 2G

  ollama:
    build: ollama
    ports:
      - "11434:11434"
    env_file:
      - .env
    volumes:
      - backend-vol:/ollama
    networks:
      - backend-net
    entrypoint: ["/usr/bin/bash", "/get_models.sh"]

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge

volumes:
  backend-vol:
    driver: local