services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  backend:
    build: ./backend
    env_file:
      - .env
    # ports:
    #   - "8000:8000"
    networks:
      - backend-net
    volumes:
      - ./backend:/backend-code
    depends_on:
      - ollama

  ollama:
    build: ollama
    # ports:
    #   - "11434:11434"
    env_file:
      - .env
    volumes:
      - backend-vol:/ollama
    networks:
      - backend-net
    entrypoint: ["/usr/bin/bash", "/get_models.sh"]

  frontend:
    labels:
      - "traefik.http.routers.frontend.rule=Host(`keysentinel.xyz`)"
    build: ./frontend
    # ports:
    #   - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge

volumes:
  backend-vol:
    driver: local
