[project]
name = "backend"
version = "0.1.0"
description = "backend for sweng project"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "fastapi[standard]<1.0.0,>=0.115.7",
  "pydantic==2.10.6 ",
  "pytest==8.3.4",
]
